const types = {
  // User actions
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_LOGOUT: "USER_LOGOUT",

  // User actions
  USER_CHECK_SESSION: "USER_CHECK_SESSION",
  USER_CHECK_SESSION_SUCCESS: "USER_CHECK_SESSION_SUCCESS",
  USER_CHECK_SESSION_FAILURE: "USER_CHECK_SESSION_FAILURE",

  // Profile creation
  CREATE_PROFILE: "CREATE_PROFILE",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  CREATE_PROFILE_FAILURE: "CREATE_PROFILE_FAILURE"
};

export default types;