const types = {
  // User actions
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_LOGOUT: "USER_LOGOUT",

  // Session
  USER_CHECK_SESSION: "USER_CHECK_SESSION",
  USER_CHECK_SESSION_SUCCESS: "USER_CHECK_SESSION_SUCCESS",
  USER_CHECK_SESSION_FAILURE: "USER_CHECK_SESSION_FAILURE",

  // Profile creation
  CREATE_PROFILE: "CREATE_PROFILE",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  CREATE_PROFILE_FAILURE: "CREATE_PROFILE_FAILURE",

  // List dragons
  FETCH_DRAGONS: "FETCH_DRAGONS_DRAGONS",
  FETCH_DRAGONS_SUCCESS: "FETCH_DRAGONS_SUCCESS",
  FETCH_DRAGONS_FAILURE: "FETCH_DRAGONS_FAILURE",

  // Get a dragon
  FETCH_DRAGON: "FETCH_DRAGON",
  FETCH_DRAGON_SUCCESS: "FETCH_DRAGON_SUCCESS",
  FETCH_DRAGON_FAILURE: "FETCH_DRAGON_FAILURE",

  // Create a dragon
  CREATE_DRAGON: "CREATE_DRAGON",
  CREATE_DRAGON_SUCCESS: "CREATE_DRAGON_SUCCESS",
  CREATE_DRAGON_FAILURE: "CREATE_DRAGON_FAILURE",

  // Update a dragon
  UPDATE_DRAGON: "UPDATE_DRAGON",
  UPDATE_DRAGON_SUCCESS: "UPDATE_DRAGON_SUCCESS",
  UPDATE_DRAGON_FAILURE: "UPDATE_DRAGON_FAILURE",

  // Delete a dragon
  DELETE_DRAGON: "DELETE_DRAGON",
  DELETE_DRAGON_SUCCESS: "DELETE_DRAGON_SUCCESS",
  DELETE_DRAGON_FAILURE: "DELETE_DRAGON_FAILURE"
};

export default types;